#Probar distinos requests , separarlos con ###

# Mis variables:
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE3LCJzZXNzaW9uSWQiOiIxMjNjYmRjMy1mNWE5LTRiNjAtOGRhOC0xNmFhM2M3MDg5NTkiLCJpYXQiOjE2ODk2MTM1NjJ9.2aJLn5gRT3DWFnO3M2HLgDDLRLCDg-k6tdbjY-117gw
@baseUrl = https://127.0.0.1:8000/API/v1

# --------------------------------------------------------
#                   Quasar Usuarios
# --------------------------------------------------------
### Test API
GET {{baseUrl}}/usuarios

### Lista de Usuarios
GET {{baseUrl}}/list_usuarios

### Crear Usuario (GET)
POST {{baseUrl}}/create_usuario
?txt_user=Tomas
&txt_pass=user1

### Crear Usuario (POST Json)
POST {{baseUrl}}/create_usuario
content-type: application/json

{
  "txt_user":"TomasJosn",
  "txt_pass":"12345"
}

### Eliminar Usuario
POST {{baseUrl}}/delete_usuario/17

### Eliminar todos los usuarios "Tomas"
DELETE {{baseUrl}}/delete_tomas

### Soft Delete todos los usaruis "Tomas"
GET {{baseUrl}}/soft_delete





# --------------------------------------------------------
#                   Quasar Categorias
# --------------------------------------------------------

### Lista de Categorias
GET {{baseUrl}}/list_categorias

### Crear Categoria (POST Json)
POST {{baseUrl}}/create_categoria
content-type: application/json

{
  "txt_categoria":"Urgente"
}

### Eliminar Categoría
POST {{baseUrl}}/delete_categoria/1

# --------------------------------------------------------
#                   Quasar Notas
# --------------------------------------------------------

@idUserForNotas = 7

### Lista de Notas Totales
GET {{baseUrl}}/list_notas

### Lista de Notas de Usuario
GET {{baseUrl}}/list_notas/{{idUserForNotas}}

### Crear Nota
POST {{baseUrl}}/save_nota/{{idUserForNotas}}
content-type: application/json

{
  "txt_nota":"Mi nota de tomasito",
  "txt_info":"Descripción 🤣🤣 de nota con tomasito",
  "categoriasIds":[1,4,99, "abc",1]
}

### Update Nota
POST {{baseUrl}}/save_nota/{{idUserForNotas}}/14
content-type: application/json

{
  "txt_nota":"Mi nota actualizada",
  "txt_info":"Descripción 🤣🤣 de nota con tomasito",
  "categoriasIds":[1,4,99, "abc",5]
}

### Eliminar Nota
POST {{baseUrl}}/delete_nota/5


### Obtener Notas previas a una semana
GET {{baseUrl}}/list_notas/{{idUserForNotas}}/antiguas

# --------------------------------------------------------
#                   Testing Endpoints
# --------------------------------------------------------
### Ping-Poing
GET {{baseUrl}}/test/ping

### Welcome
GET {{baseUrl}}/test/

### Bearer Token Test
GET {{baseUrl}}/test/profile
Authorization: Bearer {{token}}