#Probar distinos requests , separarlos con ###

# Mis variables:
@token = JwT-TOKEN123
@baseUrl = https://127.0.0.1:8000/API/v1

# --------------------------------------------------------
#                   Quasar Usuarios
# --------------------------------------------------------
### Test API
GET {{baseUrl}}/usuarios

### Lista de Usuarios
GET {{baseUrl}}/list_usuarios

### Crear Usuario (POST Json)
POST {{baseUrl}}/save_usuario
content-type: application/json

{
  "txt_user":"Tomas",
  "txt_pass":"12345"
}

### Update Usuario
PUT {{baseUrl}}/save_usuario/18
content-type: application/json

{
  "txt_user":"Tomassss18",
  "txt_pass":"12345666"
}

### Eliminar Usuario
DELETE {{baseUrl}}/delete_usuario/15



# --------------------------------------------------------
#                   Quasar Categorias
# --------------------------------------------------------

### Lista de Categorias
GET {{baseUrl}}/list_categorias

### Crear Categoria (POST Json)
POST {{baseUrl}}/save_categoria
content-type: application/json

{
  "txt_categoria":"borrame"
}

### Update Categoria
PUT {{baseUrl}}/save_categoria/9
content-type: application/json

{
  "txt_categoria":"Mejor no me borres"
}

### Eliminar Categoría
DELETE {{baseUrl}}/delete_categoria/7



# --------------------------------------------------------
#                   Quasar Notas
# --------------------------------------------------------

@idUserForNotas = 7

### Lista de Notas de Todos los usuarios
GET {{baseUrl}}/list_notas

### Lista de Notas de Usuario
GET {{baseUrl}}/list_notas/{{idUserForNotas}}

### Crear Nota
POST {{baseUrl}}/save_nota/{{idUserForNotas}}
content-type: application/json

{
  "txt_nota":"Mi nota de tomasito",
  "txt_info":"Descripción 🤣🤣 de nota con tomasito",
  "categoriasIds":[1,4,99, "abc",1]
}

### Update Nota
PUT {{baseUrl}}/save_nota/{{idUserForNotas}}/14
content-type: application/json

{
  "txt_nota":"Mi nota actualizada",
  "txt_info":"Descripción 🤣🤣 de nota",
  "categoriasIds":[1,4,99, "abc",5]
}

### Eliminar Nota
DELETE {{baseUrl}}/delete_nota/5


### Obtener Notas previas a una semana
GET {{baseUrl}}/list_notas/{{idUserForNotas}}/antiguas
